# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53ebd3ddf936c8cf6f585a1856f1d345ba7e995b13acc36166656731c3b70cc24ef5082f680257c439aa0f53eea11d7d58e775998352b860ffd0d329502cb6fd

test:
  secret_key_base: 162a49b62c273c522f1df51e99a0fce5700f68eaefa662b2307da9317d1111f305cea48133fa1aa79dea2c469097dea52b838ec87a7a5688c8b9db666b15add4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
